name: alpha innotec Heatpump
version: 2025.11.134
slug: ha-addon-ait-heatpump
description: "Read heating data (mainly temperatures) and set configurations."
arch:
- aarch64
init: false
watchdog: http://[HOST]:[PORT:5000]/livez
homeassistant_api: true
devices:
- /dev/ttyUSB0
image: ghcr.io/martinmgraf/ha-addon-ait-heatpump