name: Huawei SUN2000 Inverter
version: 2025.11.151
slug: ha-addon-huawei-sun2000
description: "Reads the current power generation data and the battery's state of charge (SoC) from the inverter."
arch:
- aarch64
init: false
watchdog: http://[HOST]:[PORT:5000]/livez
homeassistant_api: true
image: ghcr.io/martinmgraf/ha-addon-huawei-sun2000